[package]
name = "dependency_db"
version = "0.1.0"
edition = "2021"

[dependencies]
eat = { git = "https://github.com/or-n/rust-minimalist-utils.git" }
spit = { git = "https://github.com/or-n/rust-minimalist-utils.git" }
